FROM golang:1.17-alpine as build

WORKDIR /checklist

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o checklist  cmd/api/main.go

FROM alpine:latest

ENV MIGRATIONS_FOLDER_URL=file://root/db/migrations

RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /checklist .
CMD ["./checklist"]