  
version: "3.7"

services:
  app:
    build: .
    ports: 
      - 3000:3000
    depends_on:
      - db
    environment: 
      - DATABASE_URL=postgresql://postgres:123@db:5432/postgres?sslmode=disable
  db:
    image: postgres:13.3
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123